AUTOTRADE_MY_AUCTIONS = "My Auctions"
AUTOTRADE_MY_BIDS = "My Bids"
AUTOTRADE_ALL_AUCTIONS = "All Auctions"
GLOBAL_REMOVE_TAG_C = "Remove"
ACCEPT = "Accept"
GLOBAL_ZONE_TAG_C = "Zone"
GLOBAL_ITEM_TAG_C = "Item"
ALL = "All"
AUTOTRADE_WISH_LIST = "Wish list"
AUTOTRADE_REMOVE_IF_WIN = "Remove if win"

TOOLTIP_DEFAULT_COLOR.r = 0
TOOLTIP_DEFAULT_COLOR.g = 0
TOOLTIP_DEFAULT_COLOR.b = 0

TOOLTIP_DEFAULT_BACKGROUND_COLOR.r = 0
TOOLTIP_DEFAULT_BACKGROUND_COLOR.g = 0
TOOLTIP_DEFAULT_BACKGROUND_COLOR.b = 0

AUTOTRADE_ALL_AUCTIONS_TIP = "TEST"
